export const POCKETPAY_ERROR_CODES = {
  INVALID_PUBLIC_KEY: 'INVALID_PUBLIC_KEY',
  INVALID_SECRET_KEY: 'INVALID_SECRET_KEY',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_AMOUNT_PRECISION: 'INVALID_AMOUNT_PRECISION',
  INVALID_MEMO: 'INVALID_MEMO',
  SELF_PAYMENT: 'SELF_PAYMENT',
  INVALID_ASSET: 'INVALID_ASSET',
  INVALID_ASSET_CODE: 'INVALID_ASSET_CODE',
  MISSING_ASSET_ISSUER: 'MISSING_ASSET_ISSUER',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  TX_STATUS_UNKNOWN: 'TX_STATUS_UNKNOWN',
  TX_EXPIRED: 'TX_EXPIRED',
  SEND_ERROR: 'SEND_ERROR',
  TX_FETCH_ERROR: 'TX_FETCH_ERROR',
  PAYMENTS_FETCH_ERROR: 'PAYMENTS_FETCH_ERROR',
  BALANCE_ERROR: 'BALANCE_ERROR',
  TESTNET_ONLY: 'TESTNET_ONLY',
  FRIENDBOT_ERROR: 'FRIENDBOT_ERROR',
  FUND_ERROR: 'FUND_ERROR',
  MISSING_CONTRACT_ID: 'MISSING_CONTRACT_ID',
  VAULT_DEPOSIT_ERROR: 'VAULT_DEPOSIT_ERROR',
  VAULT_WITHDRAW_ERROR: 'VAULT_WITHDRAW_ERROR',
  VAULT_BALANCE_ERROR: 'VAULT_BALANCE_ERROR',
  MISSING_TRUSTLINE: 'MISSING_TRUSTLINE',
  TRUSTLINE_NOT_AUTHORIZED: 'TRUSTLINE_NOT_AUTHORIZED',
  TRUSTLINE_LIMIT_EXCEEDED: 'TRUSTLINE_LIMIT_EXCEEDED',
  UNFUNDED_DESTINATION: 'UNFUNDED_DESTINATION',
  TRUSTLINE_CHECK_ERROR: 'TRUSTLINE_CHECK_ERROR',
} as const;

export type PocketPayErrorCode =
  (typeof POCKETPAY_ERROR_CODES)[keyof typeof POCKETPAY_ERROR_CODES];

export const POCKETPAY_ERROR_CODE_CATEGORIES = {
  validation: [
    POCKETPAY_ERROR_CODES.INVALID_PUBLIC_KEY,
    POCKETPAY_ERROR_CODES.INVALID_SECRET_KEY,
    POCKETPAY_ERROR_CODES.INVALID_AMOUNT,
    POCKETPAY_ERROR_CODES.INVALID_AMOUNT_PRECISION,
    POCKETPAY_ERROR_CODES.INVALID_MEMO,
    POCKETPAY_ERROR_CODES.SELF_PAYMENT,
    POCKETPAY_ERROR_CODES.INVALID_ASSET,
    POCKETPAY_ERROR_CODES.INVALID_ASSET_CODE,
    POCKETPAY_ERROR_CODES.MISSING_ASSET_ISSUER,
  ],
  network: [
    POCKETPAY_ERROR_CODES.ACCOUNT_NOT_FOUND,
    POCKETPAY_ERROR_CODES.TX_STATUS_UNKNOWN,
    POCKETPAY_ERROR_CODES.TX_EXPIRED,
    POCKETPAY_ERROR_CODES.TX_FETCH_ERROR,
    POCKETPAY_ERROR_CODES.PAYMENTS_FETCH_ERROR,
    POCKETPAY_ERROR_CODES.BALANCE_ERROR,
    POCKETPAY_ERROR_CODES.FRIENDBOT_ERROR,
    POCKETPAY_ERROR_CODES.FUND_ERROR,
  ],
  transaction: [
    POCKETPAY_ERROR_CODES.PAYMENT_FAILED,
    POCKETPAY_ERROR_CODES.SEND_ERROR,
  ],
  trustline: [
    POCKETPAY_ERROR_CODES.MISSING_TRUSTLINE,
    POCKETPAY_ERROR_CODES.TRUSTLINE_NOT_AUTHORIZED,
    POCKETPAY_ERROR_CODES.TRUSTLINE_LIMIT_EXCEEDED,
    POCKETPAY_ERROR_CODES.UNFUNDED_DESTINATION,
    POCKETPAY_ERROR_CODES.TRUSTLINE_CHECK_ERROR,
  ],
  soroban: [
    POCKETPAY_ERROR_CODES.MISSING_CONTRACT_ID,
    POCKETPAY_ERROR_CODES.VAULT_DEPOSIT_ERROR,
    POCKETPAY_ERROR_CODES.VAULT_WITHDRAW_ERROR,
    POCKETPAY_ERROR_CODES.VAULT_BALANCE_ERROR,
  ],
  configuration: [POCKETPAY_ERROR_CODES.TESTNET_ONLY],
} as const satisfies Record<string, readonly PocketPayErrorCode[]>;

export type PocketPayErrorCodeCategory = keyof typeof POCKETPAY_ERROR_CODE_CATEGORIES;

export function isPocketPayErrorCode(code: string): code is PocketPayErrorCode {
  return Object.values(POCKETPAY_ERROR_CODES).includes(code as PocketPayErrorCode);
}